# Generated by Django 4.0 on 2023-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exam_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
