# Generated by Django 4.0 on 2023-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_question_student_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
