# Generated by Django 4.0 on 2023-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
