# Generated by Django 4.0 on 2023-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_question_time_exam_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_enter',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_mark',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student_answer',
        ),
    ]
