# Generated by Django 4.0 on 2023-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_question_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='can_view_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
