# Generated by Django 4.0 on 2023-03-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_exam_can_view_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
    ]
