# Generated by Django 4.0 on 2023-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_exam_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='c_1',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_2',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_3',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_4',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='note',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
