# Generated by Django 4.0 on 2023-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_question_c_1_alter_question_c_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
