# Generated by Django 4.0 on 2023-03-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='exam',
        ),
        migrations.AddField(
            model_name='round',
            name='exam',
            field=models.ManyToManyField(related_name='round_exams', to='app.Exam'),
        ),
    ]
