# Generated by Django 4.0 on 2023-03-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_round_exam_round_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='level',
        ),
    ]
