# Generated by Django 4.0 on 2023-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_round_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
